version: "3.8"
services:
  nats:
    image: nats:2.10-alpine
    command: >
      -js
      -m 8222
      --http_port 8222
      --server_name nats-cardiocheck
    ports:
      - "4222:4222"   # client
      - "8222:8222"   # monitoramento HTTP (NATS)
    restart: unless-stopped